#!/usr/bin/env bash
# Configure your Nginx server such that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Create a new configuration file
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /custom_404.html;
}" > /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

service nginx restart
