#!/usr/bin/env bash
# Configures Nginx with custom HTTP header of web-01 and web-02

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Set the hostname as the value for the custom HTTP header "X-Served-By"
sudo sed -i "16i\add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo service nginx restart
