#!/usr/bin/env bash
#Displays the listening Ports

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
sudo ss -tunlp | awk 'NR>1 {print $1 " " $2 " " $3 " " $4 " " $5 " " $6 " " $7}'
echo ""
echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
sudo ss -xlp | awk 'NR>1 {print $1 " " $2 " " $3 " " $4 " " $5 " " $6 " " $7}'
