#!/usr/bin/env bash
#The script creates the highlander process
function sigterm_func {
	echo "I am invincible!!!"
	exit 0
}

trap sigterm_func SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
