#!/usr/bin/env bash
# Script to display "Best School" 10 times with a condition on the 9th iteration

counter=0

while [[ $counter -lt 10 ]]; do
    if [[ $counter -eq 8 ]]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
