#!/usr/bin/env bash
#Configures an Ubuntu server with custom requirements.

# Adding a localhost entry to /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

# Adding facebook.com entry to /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
