#!/usr/bin/env bash
# Script runs the "whoami" command as a specified user

# Check if a username has been provided
if [ -z "$1" ]; then
    echo "Please provide a username as an argument."
    exit 1
fi

# Run the whoami command under the user passed as an argument
sudo -u "$1" whoami

